/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import presenter.PresenterIncluder;
import presenter.PresenterObserver;
import presenter.PresenterRemover;
import presenter.PresenterSaver;

/**
 *
 * @author The_Z
 */
public class Interface extends javax.swing.JFrame {
    
            private PresenterObserver pobserver;
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(getParent());
        pobserver = new PresenterObserver();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        tituloConfigPanel = new javax.swing.JPanel();
        configButton = new javax.swing.JButton();
        dadosTempoPanel = new javax.swing.JPanel();
        dataDadosTempoLabel = new javax.swing.JLabel();
        tempDadosTempoLabel = new javax.swing.JLabel();
        umiDadosTempoLabel = new javax.swing.JLabel();
        presDadosTempoLabel = new javax.swing.JLabel();
        dataDadosTempoFTField = new javax.swing.JFormattedTextField();
        tempDadosTempoTField = new javax.swing.JTextField();
        umiDadosTempoTField = new javax.swing.JTextField();
        presDadosTempoTField = new javax.swing.JTextField();
        dadosTempoTituloPanel = new javax.swing.JPanel();
        dadosTempoTituloLabel = new javax.swing.JLabel();
        incluirDadosTempoButton = new javax.swing.JButton();
        ultimaAtualizacaoPanel = new javax.swing.JPanel();
        dataUltimaAtualizacaoLabel = new javax.swing.JLabel();
        tempUltimaAtualizacaoLabel = new javax.swing.JLabel();
        umiUltimaAtualizacaoLabel = new javax.swing.JLabel();
        presUltimaAtualizacaoLabel = new javax.swing.JLabel();
        ultimaAtualizacaoTituloPanel = new javax.swing.JPanel();
        ultimaAtualizacaoTituloLabel = new javax.swing.JLabel();
        dataUltimaAtualizacaoFinalLabel = new javax.swing.JLabel();
        tempUltimaAtualizacaoFinalLabel = new javax.swing.JLabel();
        umiUltimaAtualizacaoFinalLabel = new javax.swing.JLabel();
        presUltimaAtualizacaoFinalLabel = new javax.swing.JLabel();
        dadosMediosPanel = new javax.swing.JPanel();
        periodoDadosMediosLabel = new javax.swing.JLabel();
        tempDadosMediosLabel = new javax.swing.JLabel();
        umiDadosMediosLabel = new javax.swing.JLabel();
        presDadosMediosLabel = new javax.swing.JLabel();
        dadosMedioTituloPanel = new javax.swing.JPanel();
        dadosMediosTituloLabel = new javax.swing.JLabel();
        regDadosMedioLabel = new javax.swing.JLabel();
        tempDadosMediosFinalLabel = new javax.swing.JLabel();
        umiDadosMediosFinalLabel = new javax.swing.JLabel();
        presDadosMediosFinalLabel = new javax.swing.JLabel();
        regDadosMediosFinalLabel = new javax.swing.JLabel();
        periodoDadosMediosComboBox = new javax.swing.JComboBox<>();
        registrosPanel = new javax.swing.JPanel();
        registrosTituloPanel = new javax.swing.JPanel();
        registrosTituloLabel = new javax.swing.JLabel();
        registroScrollPane = new javax.swing.JScrollPane();
        registroTable = new javax.swing.JTable();
        regRemover = new javax.swing.JButton();
        totalRegLabel = new javax.swing.JLabel();
        totalRegFinal = new javax.swing.JLabel();
        configFrame = new javax.swing.JInternalFrame();
        configPanel = new javax.swing.JPanel();
        logConfigLabel = new javax.swing.JLabel();
        configTituloPanel = new javax.swing.JPanel();
        configTituloLabel = new javax.swing.JLabel();
        salvarConfigButton = new javax.swing.JButton();
        logConfigComboBox = new javax.swing.JComboBox<>();
        fecharConfig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloPanel.setBackground(new java.awt.Color(58, 167, 237));

        tituloLabel.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        tituloLabel.setText("Weather Data Display");

        tituloConfigPanel.setBackground(new java.awt.Color(156, 202, 230));

        configButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        configButton.setText("Configuração");
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tituloConfigPanelLayout = new javax.swing.GroupLayout(tituloConfigPanel);
        tituloConfigPanel.setLayout(tituloConfigPanelLayout);
        tituloConfigPanelLayout.setHorizontalGroup(
            tituloConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloConfigPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(configButton))
        );
        tituloConfigPanelLayout.setVerticalGroup(
            tituloConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloConfigPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(configButton))
        );

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tituloConfigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloConfigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dadosTempoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dataDadosTempoLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        dataDadosTempoLabel.setText("Data");

        tempDadosTempoLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tempDadosTempoLabel.setText("Temperatura");

        umiDadosTempoLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        umiDadosTempoLabel.setText("Umidade");

        presDadosTempoLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        presDadosTempoLabel.setText("Pressão");

        dataDadosTempoFTField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-y"))));
        dataDadosTempoFTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDadosTempoFTFieldActionPerformed(evt);
            }
        });

        dadosTempoTituloPanel.setBackground(new java.awt.Color(156, 202, 230));

        dadosTempoTituloLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        dadosTempoTituloLabel.setText("Dados do Tempo");

        javax.swing.GroupLayout dadosTempoTituloPanelLayout = new javax.swing.GroupLayout(dadosTempoTituloPanel);
        dadosTempoTituloPanel.setLayout(dadosTempoTituloPanelLayout);
        dadosTempoTituloPanelLayout.setHorizontalGroup(
            dadosTempoTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosTempoTituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dadosTempoTituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dadosTempoTituloPanelLayout.setVerticalGroup(
            dadosTempoTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosTempoTituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dadosTempoTituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        incluirDadosTempoButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        incluirDadosTempoButton.setText("Incluir");
        incluirDadosTempoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirDadosTempoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dadosTempoPanelLayout = new javax.swing.GroupLayout(dadosTempoPanel);
        dadosTempoPanel.setLayout(dadosTempoPanelLayout);
        dadosTempoPanelLayout.setHorizontalGroup(
            dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dadosTempoTituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosTempoPanelLayout.createSequentialGroup()
                .addGroup(dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dadosTempoPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(incluirDadosTempoButton))
                    .addGroup(dadosTempoPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadosTempoPanelLayout.createSequentialGroup()
                                .addGroup(dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataDadosTempoLabel)
                                    .addComponent(presDadosTempoLabel))
                                .addGap(39, 39, 39)
                                .addGroup(dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(presDadosTempoTField)
                                    .addComponent(dataDadosTempoFTField, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                            .addGroup(dadosTempoPanelLayout.createSequentialGroup()
                                .addGroup(dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tempDadosTempoLabel)
                                    .addComponent(umiDadosTempoLabel))
                                .addGap(18, 18, 18)
                                .addGroup(dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(umiDadosTempoTField)
                                    .addComponent(tempDadosTempoTField))))))
                .addGap(25, 25, 25))
        );
        dadosTempoPanelLayout.setVerticalGroup(
            dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosTempoPanelLayout.createSequentialGroup()
                .addComponent(dadosTempoTituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDadosTempoLabel)
                    .addComponent(dataDadosTempoFTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempDadosTempoLabel)
                    .addComponent(tempDadosTempoTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umiDadosTempoLabel)
                    .addComponent(umiDadosTempoTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosTempoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presDadosTempoLabel)
                    .addComponent(presDadosTempoTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incluirDadosTempoButton)
                .addContainerGap())
        );

        ultimaAtualizacaoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dataUltimaAtualizacaoLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        dataUltimaAtualizacaoLabel.setText("Data");

        tempUltimaAtualizacaoLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tempUltimaAtualizacaoLabel.setText("Temperatura");

        umiUltimaAtualizacaoLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        umiUltimaAtualizacaoLabel.setText("Umidade");

        presUltimaAtualizacaoLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        presUltimaAtualizacaoLabel.setText("Pressão");

        ultimaAtualizacaoTituloPanel.setBackground(new java.awt.Color(156, 202, 230));

        ultimaAtualizacaoTituloLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        ultimaAtualizacaoTituloLabel.setText("Ultima Atualização do Tempo");

        javax.swing.GroupLayout ultimaAtualizacaoTituloPanelLayout = new javax.swing.GroupLayout(ultimaAtualizacaoTituloPanel);
        ultimaAtualizacaoTituloPanel.setLayout(ultimaAtualizacaoTituloPanelLayout);
        ultimaAtualizacaoTituloPanelLayout.setHorizontalGroup(
            ultimaAtualizacaoTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ultimaAtualizacaoTituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ultimaAtualizacaoTituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ultimaAtualizacaoTituloPanelLayout.setVerticalGroup(
            ultimaAtualizacaoTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ultimaAtualizacaoTituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ultimaAtualizacaoTituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataUltimaAtualizacaoFinalLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        dataUltimaAtualizacaoFinalLabel.setText("DATA");

        tempUltimaAtualizacaoFinalLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tempUltimaAtualizacaoFinalLabel.setText("TEMPERATURA");

        umiUltimaAtualizacaoFinalLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        umiUltimaAtualizacaoFinalLabel.setText("UMIDADE");

        presUltimaAtualizacaoFinalLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        presUltimaAtualizacaoFinalLabel.setText("PRESSÃO");

        javax.swing.GroupLayout ultimaAtualizacaoPanelLayout = new javax.swing.GroupLayout(ultimaAtualizacaoPanel);
        ultimaAtualizacaoPanel.setLayout(ultimaAtualizacaoPanelLayout);
        ultimaAtualizacaoPanelLayout.setHorizontalGroup(
            ultimaAtualizacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ultimaAtualizacaoTituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ultimaAtualizacaoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ultimaAtualizacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ultimaAtualizacaoPanelLayout.createSequentialGroup()
                        .addComponent(presUltimaAtualizacaoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(presUltimaAtualizacaoFinalLabel))
                    .addGroup(ultimaAtualizacaoPanelLayout.createSequentialGroup()
                        .addComponent(umiUltimaAtualizacaoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(umiUltimaAtualizacaoFinalLabel))
                    .addGroup(ultimaAtualizacaoPanelLayout.createSequentialGroup()
                        .addComponent(tempUltimaAtualizacaoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tempUltimaAtualizacaoFinalLabel))
                    .addGroup(ultimaAtualizacaoPanelLayout.createSequentialGroup()
                        .addComponent(dataUltimaAtualizacaoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataUltimaAtualizacaoFinalLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ultimaAtualizacaoPanelLayout.setVerticalGroup(
            ultimaAtualizacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ultimaAtualizacaoPanelLayout.createSequentialGroup()
                .addComponent(ultimaAtualizacaoTituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ultimaAtualizacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataUltimaAtualizacaoLabel)
                    .addComponent(dataUltimaAtualizacaoFinalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ultimaAtualizacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempUltimaAtualizacaoLabel)
                    .addComponent(tempUltimaAtualizacaoFinalLabel))
                .addGap(18, 18, 18)
                .addGroup(ultimaAtualizacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umiUltimaAtualizacaoLabel)
                    .addComponent(umiUltimaAtualizacaoFinalLabel))
                .addGap(18, 18, 18)
                .addGroup(ultimaAtualizacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presUltimaAtualizacaoLabel)
                    .addComponent(presUltimaAtualizacaoFinalLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dadosMediosPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        periodoDadosMediosLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        periodoDadosMediosLabel.setText("Período");

        tempDadosMediosLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tempDadosMediosLabel.setText("Temperatura");

        umiDadosMediosLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        umiDadosMediosLabel.setText("Umidade");

        presDadosMediosLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        presDadosMediosLabel.setText("Pressão");

        dadosMedioTituloPanel.setBackground(new java.awt.Color(156, 202, 230));

        dadosMediosTituloLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        dadosMediosTituloLabel.setText("Dados Médios");

        javax.swing.GroupLayout dadosMedioTituloPanelLayout = new javax.swing.GroupLayout(dadosMedioTituloPanel);
        dadosMedioTituloPanel.setLayout(dadosMedioTituloPanelLayout);
        dadosMedioTituloPanelLayout.setHorizontalGroup(
            dadosMedioTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosMedioTituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dadosMediosTituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dadosMedioTituloPanelLayout.setVerticalGroup(
            dadosMedioTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosMedioTituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dadosMediosTituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        regDadosMedioLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        regDadosMedioLabel.setText("Nº Registros");

        tempDadosMediosFinalLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tempDadosMediosFinalLabel.setText("TEMPERATURA");

        umiDadosMediosFinalLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        umiDadosMediosFinalLabel.setText("UMIDADE");

        presDadosMediosFinalLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        presDadosMediosFinalLabel.setText("PRESSÃO");

        regDadosMediosFinalLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        regDadosMediosFinalLabel.setText("Nº REGISTROS");

        periodoDadosMediosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semanal", "Diário", "Mensal" }));
        periodoDadosMediosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodoDadosMediosComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dadosMediosPanelLayout = new javax.swing.GroupLayout(dadosMediosPanel);
        dadosMediosPanel.setLayout(dadosMediosPanelLayout);
        dadosMediosPanelLayout.setHorizontalGroup(
            dadosMediosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dadosMedioTituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosMediosPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(dadosMediosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dadosMediosPanelLayout.createSequentialGroup()
                        .addComponent(tempDadosMediosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tempDadosMediosFinalLabel)
                        .addGap(1, 1, 1))
                    .addGroup(dadosMediosPanelLayout.createSequentialGroup()
                        .addGroup(dadosMediosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(periodoDadosMediosLabel)
                            .addComponent(umiDadosMediosLabel)
                            .addComponent(presDadosMediosLabel)
                            .addComponent(regDadosMedioLabel))
                        .addGap(18, 18, 18)
                        .addGroup(dadosMediosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(umiDadosMediosFinalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(presDadosMediosFinalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regDadosMediosFinalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dadosMediosPanelLayout.createSequentialGroup()
                                .addComponent(periodoDadosMediosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE)))))
                .addGap(24, 24, 24))
        );
        dadosMediosPanelLayout.setVerticalGroup(
            dadosMediosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosMediosPanelLayout.createSequentialGroup()
                .addComponent(dadosMedioTituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosMediosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodoDadosMediosLabel)
                    .addComponent(periodoDadosMediosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosMediosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempDadosMediosLabel)
                    .addComponent(tempDadosMediosFinalLabel))
                .addGap(18, 18, 18)
                .addGroup(dadosMediosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umiDadosMediosLabel)
                    .addComponent(umiDadosMediosFinalLabel))
                .addGap(18, 18, 18)
                .addGroup(dadosMediosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presDadosMediosLabel)
                    .addComponent(presDadosMediosFinalLabel))
                .addGap(18, 18, 18)
                .addGroup(dadosMediosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regDadosMedioLabel)
                    .addComponent(regDadosMediosFinalLabel))
                .addGap(43, 43, 43))
        );

        registrosPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        registrosTituloPanel.setBackground(new java.awt.Color(156, 202, 230));

        registrosTituloLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        registrosTituloLabel.setText("Registros");

        javax.swing.GroupLayout registrosTituloPanelLayout = new javax.swing.GroupLayout(registrosTituloPanel);
        registrosTituloPanel.setLayout(registrosTituloPanelLayout);
        registrosTituloPanelLayout.setHorizontalGroup(
            registrosTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrosTituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrosTituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registrosTituloPanelLayout.setVerticalGroup(
            registrosTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrosTituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrosTituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        registroTable.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        registroTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Temperatura", "Umidade", "Pressão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        registroScrollPane.setViewportView(registroTable);

        regRemover.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        regRemover.setText("Remover");
        regRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrosPanelLayout = new javax.swing.GroupLayout(registrosPanel);
        registrosPanel.setLayout(registrosPanelLayout);
        registrosPanelLayout.setHorizontalGroup(
            registrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrosTituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registroScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrosPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(regRemover)))
                .addContainerGap())
        );
        registrosPanelLayout.setVerticalGroup(
            registrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrosPanelLayout.createSequentialGroup()
                .addComponent(registrosTituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registroScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalRegLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        totalRegLabel.setText("Total de Registros:");

        totalRegFinal.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        totalRegFinal.setText("0");

        configFrame.setVisible(true);

        configPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        logConfigLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        logConfigLabel.setText("Log");

        configTituloPanel.setBackground(new java.awt.Color(156, 202, 230));

        configTituloLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        configTituloLabel.setText("Configuração do Sistema");

        javax.swing.GroupLayout configTituloPanelLayout = new javax.swing.GroupLayout(configTituloPanel);
        configTituloPanel.setLayout(configTituloPanelLayout);
        configTituloPanelLayout.setHorizontalGroup(
            configTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configTituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(configTituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        configTituloPanelLayout.setVerticalGroup(
            configTituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configTituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(configTituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        salvarConfigButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        salvarConfigButton.setText("Salvar");
        salvarConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarConfigButtonActionPerformed(evt);
            }
        });

        logConfigComboBox.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        logConfigComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JSON", "XML" }));

        fecharConfig.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        fecharConfig.setLabel("Fechar");
        fecharConfig.setMaximumSize(new java.awt.Dimension(63, 21));
        fecharConfig.setMinimumSize(new java.awt.Dimension(63, 21));
        fecharConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(configTituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addComponent(logConfigLabel)
                        .addGap(18, 18, 18)
                        .addComponent(logConfigComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addComponent(fecharConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(salvarConfigButton)))
                .addContainerGap())
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addComponent(configTituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logConfigLabel)
                    .addComponent(logConfigComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salvarConfigButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fecharConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout configFrameLayout = new javax.swing.GroupLayout(configFrame.getContentPane());
        configFrame.getContentPane().setLayout(configFrameLayout);
        configFrameLayout.setHorizontalGroup(
            configFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configFrameLayout.createSequentialGroup()
                .addComponent(configPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        configFrameLayout.setVerticalGroup(
            configFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(configPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dadosTempoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dadosMediosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(configFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ultimaAtualizacaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(registrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(totalRegLabel)
                        .addGap(18, 18, 18)
                        .addComponent(totalRegFinal)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dadosTempoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(configFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadosMediosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ultimaAtualizacaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalRegLabel)
                    .addComponent(totalRegFinal)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incluirDadosTempoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirDadosTempoButtonActionPerformed
        PresenterIncluder.incluirReport(dataDadosTempoFTField.getText(), tempDadosTempoTField.getText(), umiDadosTempoTField.getText(), presDadosTempoTField.getText());
        pobserver.update();
    }//GEN-LAST:event_incluirDadosTempoButtonActionPerformed

    private void periodoDadosMediosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodoDadosMediosComboBoxActionPerformed
        pobserver.update();
    }//GEN-LAST:event_periodoDadosMediosComboBoxActionPerformed

    private void salvarConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarConfigButtonActionPerformed
        try {
            PresenterSaver.salvarConfig(logConfigComboBox.getSelectedIndex());
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salvarConfigButtonActionPerformed

    private void dataDadosTempoFTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDadosTempoFTFieldActionPerformed
        //NÃO USAR ISSO
    }//GEN-LAST:event_dataDadosTempoFTFieldActionPerformed

    private void regRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regRemoverActionPerformed
        PresenterRemover.removerReport(registroTable.getSelectedRow());
        pobserver.update();
    }//GEN-LAST:event_regRemoverActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        configFrame.setVisible(true);
    }//GEN-LAST:event_configButtonActionPerformed

    private void fecharConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharConfigActionPerformed
        configFrame.setVisible(false);
    }//GEN-LAST:event_fecharConfigActionPerformed

    public JFormattedTextField getDataDadosTempoFTField() {
        return dataDadosTempoFTField;
    }

    public void setDataDadosTempoFTField(JFormattedTextField dataDadosTempoFTField) {
        this.dataDadosTempoFTField = dataDadosTempoFTField;
    }

    public JTextField getPresDadosTempoTField() {
        return presDadosTempoTField;
    }

    public void setPresDadosTempoTField(JTextField presDadosTempoTField) {
        this.presDadosTempoTField = presDadosTempoTField;
    }

    public JTextField getTempDadosTempoTField() {
        return tempDadosTempoTField;
    }

    public void setTempDadosTempoTField(JTextField tempDadosTempoTField) {
        this.tempDadosTempoTField = tempDadosTempoTField;
    }

    public JTextField getUmiDadosTempoTField() {
        return umiDadosTempoTField;
    }

    public void setUmiDadosTempoTField(JTextField umiDadosTempoTField) {
        this.umiDadosTempoTField = umiDadosTempoTField;
    }

    public JLabel getDataUltimaAtualizacaoFinalLabel() {
        return dataUltimaAtualizacaoFinalLabel;
    }

    public void setDataUltimaAtualizacaoFinalLabel(JLabel dataUltimaAtualizacaoFinalLabel) {
        this.dataUltimaAtualizacaoFinalLabel = dataUltimaAtualizacaoFinalLabel;
    }

    public JLabel getPresUltimaAtualizacaoFinalLabel() {
        return presUltimaAtualizacaoFinalLabel;
    }

    public void setPresUltimaAtualizacaoFinalLabel(JLabel presUltimaAtualizacaoFinalLabel) {
        this.presUltimaAtualizacaoFinalLabel = presUltimaAtualizacaoFinalLabel;
    }

    public JLabel getTempUltimaAtualizacaoFinalLabel() {
        return tempUltimaAtualizacaoFinalLabel;
    }

    public void setTempUltimaAtualizacaoFinalLabel(JLabel tempUltimaAtualizacaoFinalLabel) {
        this.tempUltimaAtualizacaoFinalLabel = tempUltimaAtualizacaoFinalLabel;
    }

    public JLabel getUmiUltimaAtualizacaoFinalLabel() {
        return umiUltimaAtualizacaoFinalLabel;
    }

    public void setUmiUltimaAtualizacaoFinalLabel(JLabel umiUltimaAtualizacaoFinalLabel) {
        this.umiUltimaAtualizacaoFinalLabel = umiUltimaAtualizacaoFinalLabel;
    }

    public JLabel getTotalRegFinal() {
        return totalRegFinal;
    }

    public void setTotalRegFinal(JLabel totalRegFinal) {
        this.totalRegFinal = totalRegFinal;
    }

    public JComboBox<String> getPeriodoDadosMediosComboBox() {
        return periodoDadosMediosComboBox;
    }

    public void setPeriodoDadosMediosComboBox(JComboBox<String> periodoDadosMediosComboBox) {
        this.periodoDadosMediosComboBox = periodoDadosMediosComboBox;
    }

    public JLabel getPresDadosMediosFinalLabel() {
        return presDadosMediosFinalLabel;
    }

    public void setPresDadosMediosFinalLabel(JLabel presDadosMediosFinalLabel) {
        this.presDadosMediosFinalLabel = presDadosMediosFinalLabel;
    }

    public JLabel getRegDadosMediosFinalLabel() {
        return regDadosMediosFinalLabel;
    }

    public void setRegDadosMediosFinalLabel(JLabel regDadosMediosFinalLabel) {
        this.regDadosMediosFinalLabel = regDadosMediosFinalLabel;
    }

    public JLabel getTempDadosMediosFinalLabel() {
        return tempDadosMediosFinalLabel;
    }

    public void setTempDadosMediosFinalLabel(JLabel tempDadosMediosFinalLabel) {
        this.tempDadosMediosFinalLabel = tempDadosMediosFinalLabel;
    }

    public JLabel getUmiDadosMediosFinalLabel() {
        return umiDadosMediosFinalLabel;
    }

    public void setUmiDadosMediosFinalLabel(JLabel umiDadosMediosFinalLabel) {
        this.umiDadosMediosFinalLabel = umiDadosMediosFinalLabel;
    }

    public JTable getRegistroTable() {
        return registroTable;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configButton;
    private javax.swing.JInternalFrame configFrame;
    private javax.swing.JPanel configPanel;
    private javax.swing.JLabel configTituloLabel;
    private javax.swing.JPanel configTituloPanel;
    private javax.swing.JPanel dadosMedioTituloPanel;
    private javax.swing.JPanel dadosMediosPanel;
    private javax.swing.JLabel dadosMediosTituloLabel;
    private javax.swing.JPanel dadosTempoPanel;
    private javax.swing.JLabel dadosTempoTituloLabel;
    private javax.swing.JPanel dadosTempoTituloPanel;
    private javax.swing.JFormattedTextField dataDadosTempoFTField;
    private javax.swing.JLabel dataDadosTempoLabel;
    private javax.swing.JLabel dataUltimaAtualizacaoFinalLabel;
    private javax.swing.JLabel dataUltimaAtualizacaoLabel;
    private javax.swing.JButton fecharConfig;
    private javax.swing.JButton incluirDadosTempoButton;
    private javax.swing.JComboBox<String> logConfigComboBox;
    private javax.swing.JLabel logConfigLabel;
    private javax.swing.JComboBox<String> periodoDadosMediosComboBox;
    private javax.swing.JLabel periodoDadosMediosLabel;
    private javax.swing.JLabel presDadosMediosFinalLabel;
    private javax.swing.JLabel presDadosMediosLabel;
    private javax.swing.JLabel presDadosTempoLabel;
    private javax.swing.JTextField presDadosTempoTField;
    private javax.swing.JLabel presUltimaAtualizacaoFinalLabel;
    private javax.swing.JLabel presUltimaAtualizacaoLabel;
    private javax.swing.JLabel regDadosMedioLabel;
    private javax.swing.JLabel regDadosMediosFinalLabel;
    private javax.swing.JButton regRemover;
    private javax.swing.JScrollPane registroScrollPane;
    private javax.swing.JTable registroTable;
    private javax.swing.JPanel registrosPanel;
    private javax.swing.JLabel registrosTituloLabel;
    private javax.swing.JPanel registrosTituloPanel;
    private javax.swing.JButton salvarConfigButton;
    private javax.swing.JLabel tempDadosMediosFinalLabel;
    private javax.swing.JLabel tempDadosMediosLabel;
    private javax.swing.JLabel tempDadosTempoLabel;
    private javax.swing.JTextField tempDadosTempoTField;
    private javax.swing.JLabel tempUltimaAtualizacaoFinalLabel;
    private javax.swing.JLabel tempUltimaAtualizacaoLabel;
    private javax.swing.JPanel tituloConfigPanel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JPanel tituloPanel;
    private javax.swing.JLabel totalRegFinal;
    private javax.swing.JLabel totalRegLabel;
    private javax.swing.JPanel ultimaAtualizacaoPanel;
    private javax.swing.JLabel ultimaAtualizacaoTituloLabel;
    private javax.swing.JPanel ultimaAtualizacaoTituloPanel;
    private javax.swing.JLabel umiDadosMediosFinalLabel;
    private javax.swing.JLabel umiDadosMediosLabel;
    private javax.swing.JLabel umiDadosTempoLabel;
    private javax.swing.JTextField umiDadosTempoTField;
    private javax.swing.JLabel umiUltimaAtualizacaoFinalLabel;
    private javax.swing.JLabel umiUltimaAtualizacaoLabel;
    // End of variables declaration//GEN-END:variables
}
